"""empty message

Revision ID: 1e3d077bd721
Revises: None
Create Date: 2014-09-27 19:49:43.224392

"""

# revision identifiers, used by Alembic.
revision = '1e3d077bd721'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_category', sa.String(length=255), nullable=True),
    sa.Column('input_jobs', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('write_date', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('nic_name', sa.String(length=255), nullable=True),
    sa.Column('job', sa.String(length=255), nullable=True),
    sa.Column('major_comment', sa.String(length=255), nullable=True),
    sa.Column('major_story', sa.Text(length=65535), nullable=True),
    sa.Column('major_like', sa.String(length=255), nullable=True),
    sa.Column('check_double_major', sa.String(length=255), nullable=True),
    sa.Column('double_major', sa.String(length=255), nullable=True),
    sa.Column('job_reason', sa.Text(length=65535), nullable=True),
    sa.Column('point_major', sa.String(length=255), nullable=True),
    sa.Column('point_licence', sa.String(length=255), nullable=True),
    sa.Column('point_double_major', sa.String(length=255), nullable=True),
    sa.Column('point_reading', sa.String(length=255), nullable=True),
    sa.Column('point_extra', sa.String(length=255), nullable=True),
    sa.Column('point_ex_1', sa.String(length=255), nullable=True),
    sa.Column('point_ex_2', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('user')
    ### end Alembic commands ###
